services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    volumes:
      - sqlite-data:/app/data

    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:4-management

    hostname: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  sqlite-data:
  rabbitmq-data: